#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @see http://www.yiiframework.com/
 *
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */
define('APP_PATH', __DIR__);
define('SWOOLE_JOBS_ROOT_PATH', __DIR__);

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$config = require __DIR__ . '/config/console.php';

$application = new yii\console\Application($config);
$exitCode    = $application->run();
exit($exitCode);
